config/routes.rb
Rails.application.routes.draw do
  resources :albums
  devise_for :users
  get 'home/index'
  get 'home/show'

  get '/all_albums', to: 'albums#all_albums'
  delete "images/:id/purge",to: "albums#purge", as: "purge_image"
  resources :home



  resources :home do
    collection do
      match 'search' => 'home#search', via: [:get, :post], as: :search
    end
  end
  get 'search',to: 'albums#search'
  resources :tags


  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    has_one_attached :cover_photo
    has_many_attached :photos

    has_many :taggings,dependent: :destroy
    has_many :tags, through: :taggings



    def all_tags=(names)
        self.tags = names.split(",").map do |name|
          Tag.where(name: name).first_or_create!
        end
      end
    
      def all_tags
        tags.map(&:name).join(", ")
      end




    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :album, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :albums
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /albums or /albums.json
  # def all_albums
  #   @albums = Album.all
  # end


  def index
    #@albums = current_user.albums
    @q = current_user.albums.ransack(params[:q])
    @albums = @q.result(distinct: true)
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end
  
  # POST /albums or /albums.json
  def create
    @album = current_user.albums.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def purge
    image = ActiveStorage::Attachment.find(params[:id])
    image.purge
    redirect_back fallback_location: root_path, notice: "the image was deleted sucessfully "
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :description, :published, :cover_photo, :all_tags, :photos => [] )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
     redirect_to '/albums'
    end
   
    @q = Album.where(published: true).ransack(params[:q])
    @albums = @q.result.includes(:tags)
  end

  def search
    index
    render :index
  end



  def show
    @album=Album.find(params[:id])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-4 ">
    <%= form.label :title %>
  <%= form.text_field :title ,class: 'form-control ' %>
  </div>

  <div class="field mt-4">
    <%= form.label :cover_photo%>
       <%= form.file_field :cover_photo ,class: 'form-control' %>
  </div>

  <div class="field mt-4">
    <%= form.label :description %>
    <%= form.text_area :description ,class: 'form-control' %>
  </div>
  
  <div class="field mt-4">
    <%= form.label :tag %>
    <%= form.text_area :all_tags ,class: 'form-control' %>
  </div>


  <div class="field mt-4">
    <%= form.label :Photos %>
    <%= form.file_field :photos, :multiple => true ,class: 'form-control' %>
  </div>

  <div class="field mt-4">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions mt-4 ">
    <%= form.submit  %>
  </div>
<% end %>

app/views/albums/add_photos.html.erb
<%= form_with(model: album) do |form| %>


  <div class="field mt-4">
    <%= form.label :Photos %>
    <%= form.file_field :photos, :multiple => true ,class: 'form-control' %>
  </div>



  <div class="actions mt-4 ">
    <%= form.submit  %>
  </div>
<% end %>

app/views/albums/all_albums.html.erb
<%=render 'home/index'%>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album  , class:'btn btn-dark active mt-4 '%> |
<%= link_to 'Back', albums_path  , class:'btn btn-dark active mt-4' %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Albums</h1>
<div class='row'>
  <% @albums.each do |album| %>
  <div class='col-md-4'>
    <div class='card'>
      <div class='card-header active'><strong>Title:</strong>
        <%= album.title %> 
      </div>
      <div class='card-header color'><strong>Description:</strong>
        <%= album.description %>
      </div>
      <div class='card-body'>
          <%if album.cover_photo.attached? %>
          <%= link_to album do%>
          <%= image_tag (album.cover_photo) %>
       </div>
        <%end%>
        <%end%>
      </div>
      <div class='card-footer'>
         <%= link_to  edit_album_path(album)   do %>  <i class="fas fa-edit fa-2x mx-3  icon-cog" style="color:black "> </i> <%end%>
         <%= link_to  album, method: :delete, data: { confirm: 'Are you sure?' }   do %> <i class="far fa-trash-alt fa-2x  icon-cog" style="color:black"> </i>  <%end%> 
      </div>
    </div>
  <% end %>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path ,class: 'btn btn-primary mt-4' %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>
<div class='row'>
  <div class='col-md-8'>
    <div class="card">
     <div class="card-header">
       <strong>Title:</strong>
       <%= @album.title %>
     </div>
     <div class="card-header">
       <strong>Description:</strong>
        <%= @album.description %>
     </div>


     
     <div class="card-footer">
      <strong>Tag:</strong>
      <%=@album.all_tags%>
    </div>




     <div class="card-body">
       <%if @album.cover_photo.attached? %>
       <%= image_tag (@album.cover_photo) %>
     </div>
      <%end%>
   </div>
  </div>
  <div class='row'>
    <%@album.photos.each do |image|%>
    <div class='col-md-3'>
      <div class='card'>
       <div class="card-header"> 
          <%=link_to 'Zooms', image, class:'btn btn-success btn-sm'%> 
           <%= link_to purge_image_path(image), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger btn-sm" do %>
             <i class="fas fa-trash"></i> <%end%>
       </div>
       <div class='card-body'>
         <%=image_tag(image)%>
       </div>
     </div>
    </div> 
    <%end%>
 </div>
</div>
 
    <%# !-- Button trigger modal --> %>
<button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal"> 
  Add Photos <i class="fa fa-plus" aria-hidden="true"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> ADD PHOTOS </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with(model: @album) do |form| %>
  <div class="field mt-4">
    <%= form.label :Photos %>
    <%= form.file_field :photos, :multiple => true ,class: 'form-control' %>
  </div>
  <div class="actions mt-4 ">
    <%= form.submit  %>
  </div>
 <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_search.html.erb
<div class="container mt-3">
  <%= search_form_for @q, url: search_home_index_path,
                          html: { method: :post } do |f| %>
     <%= f.search_field :tags_name_eq %> 
     <%=f.submit "search" %> 
     
      <% end %>

  </div>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<%=render 'home/search'%>

<h1>All Published Albums </h1>

<div class='row'>
 <% @albums.each do |album| %>
 <div class='col-md-4'>
    <div class='card '>
     <div class='card-header active'><strong>Title:</strong>
        <%= album.title %> 
      </div>
    

      <div class='card-header color'><strong>Description:</strong>
          <%= album.description %>
      
      </div>
        <div class="card-header "><strong>Tags:</strong> 
      <%= album.all_tags %>
      </div>
      
      <div class='card-body '>
      
         <%if album.cover_photo.attached?%>
         <%= link_to home_path(id: album.id) do%>
         <div class ="image"><%= image_tag (album.cover_photo) %> </div>
         <%end%>
        
      </div>
     
      <%end%>
      
    </div>
  </div>
  <% end %>
</div>

app/views/home/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-8'>
    <div class="card">
  <div class="card-header">
    <strong>Title:</strong>
    <%= @album.title %>
  </div>
    <div class="card-header">
      <strong>Description:</strong>
      <%= @album.description %>
    </div>
      <div class="card-body">
    <%= image_tag (@album.cover_photo) %>
    </div>
  
    <div class='card-footer'>
      <%= link_to 'Back', root_path , class:'btn btn-dark active'%>
      <%# <%= link_to 'Edit', edit_album_path , class:'btn btn-dark active'%>
      <%# <%= link_to 'destroy', root_path , class:'btn btn-dark active'%>
    </div>
 </div>
 </div>

 <div class='row'>
   <%@album.photos.each do |image|%>
   <div class='col-md-3'>
     <div class='card'>
     <div class="card-header"> 
    <%=link_to 'Zoom', image, class:'btn btn-success btn-sm' %> 
    </div>
        <div class='card-body'>
         <%=image_tag(image)%>
        </div>

     </div>
   </div>
  <%end%>
 </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="bg-dark text-center text-white">

  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
     <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    
    <!-- Section: Social media -->




    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase"><p style="color: #0d6efd ;">Integrity</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <p href="#!" class="text-white">Unlike competing image sharing services, we don't lock your photos into one single place. YOU have full control of the management, storage and presentation of YOUR images. </p>
            </li>
            
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase"><p style="color:#0d6efd;">Diversity</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <p href="#!" class="text-white">Competitors offer few choices for stylish presentations With jAlbum you have a rich variety of themes to choose from, each offering unique functionality as well as presentation.</p>
            </li>
            
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase "> <p style="color:#0d6efd;">Convenience</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <p href="#!" class="text-white">Being a desktop software, Gallery-app makes it natural and convenient to manage large amounts of images on a regular basis.This is better done locally, and it works offline too!</p>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase"> <p style="color:#0d6efd;">Trust</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <p class="text-white">We've been in business since 2002. To date, there are over 120 million galleries published world wide Gallery-App also enjoys an extremely high user satisfaction. </p>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <div class="container p-4">
    <!-- Section: Images -->
    <section class="">
      <div class="row">
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image "
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/113.webp"
              class="w-100 hover-zoom"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/111.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/112.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/114.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light"
          >
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/115.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div
            class="bg-image hover-overlay ripple shadow-1-strong rounded"
            data-ripple-color="light">
            <img
              src="https://mdbcdn.b-cdn.net/img/new/fluid/city/116.webp"
              class="w-100"
            />
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>
      </div>
    </section>
    <!-- Section: Images -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © Copyright2022-Nik-Gallery-app.All rights reserved.
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Gallery-App", root_path, class: "navbar-brand bg-lg" %> 
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/"> </a>
            <%= link_to  root_path    do %>  <i class="fas fa-home nav-link  active">  Home  </i>  <%end%>
          
        </li>
         <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/albums/new">
           <%= link_to  new_album_path  do %>  <i class="fas fa-plus-circle nav-link active "> Add Album   </i>  <%end%>
           </a>
         </li>
      </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link active" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link active" %>
        <% else %>
        <button type="button" class="btn btn-primary btn-sm mt-2">  <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link active" %></button>
        <button type="button" class="btn btn-primary btn-sm mt-2"><%= link_to "Login", new_user_session_path, class: "nav-item nav-link active" %></button>
                
        <% end %>
        
      </ul>
    </div>
  </div>
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GalleryApp</title>

    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link rel="stylesheet" href= > 

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%=render "layouts/header" %>
  
  <div class="container">
   
    <%= yield %>
    <div class="container">
    
    <p class="alert"><%= alert %></p>
    </div>
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
     
      </div>
      <%=render "layouts/footer" %>
  </body>
</html>